# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main  
  paths:
    exclude:
      - 'WebApp/**'
      - 'HttpFunction/**'
      - 'azure-pipelines-webapp.yml'
      - 'azure-pipelines-httpfunction.yml'

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'AzureDefault'


  # Agent VM image name
  vmImageName: 'windows-latest'
stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: '$(azureSubscription)'
          subscriptionId: '343eca92-cca8-4235-8e1e-2a732b172330'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'Test'
          location: 'East US'
          templateLocation: 'Linked artifact'
          csmFile: 'AzureResourceGroup/AppConfiguration/azuredeploy.json'
          deploymentMode: 'Validation'
